repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: uv run ruff check --fix
        types: [python]

      - id: ruff-format
        name: ruff-format
        language: system
        entry: uv run ruff format
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy app
        types: [python]
        pass_filenames: false

      - id: gitmojify
        name: gitmojify
        language: system
        entry: uv run gitmojify -f
        stages: [commit-msg]

      - id: commitizen
        name: commitizen
        language: system
        entry: uv run cz check --allow-abort --commit-msg-file
        stages: [commit-msg]
